FROM maven:3.8.6-jdk-11 as libsbuild
WORKDIR /src
COPY ./core/src/com/pspace/ifs/ksan/libs/ /src/
RUN --mount=type=cache,target=/root/.m2 mvn -f /src/pom.xml install
########################################################################
FROM maven:3.8.6-jdk-11 as objmanagerbuild
WORKDIR /src
COPY ./core/src/com/pspace/ifs/ksan/objmanager/ /src/
RUN --mount=type=cache,target=/root/.m2 mvn -f /src/pom.xml install
########################################################################
FROM maven:3.8.6-jdk-11 as backendlibsbuild
WORKDIR /src
COPY ./core/backend/src/com/pspace/backend/libs/ /src/
RUN --mount=type=cache,target=/root/.m2 mvn -f /src/pom.xml install
#######################################################################
FROM maven:3.8.6-jdk-11 as build
WORKDIR /src
COPY ./core/backend/src/com/pspace/backend/lifecycle/ /src/
RUN --mount=type=cache,target=/root/.m2 mvn -f /src/pom.xml package
########################################################################
FROM openjdk:11-jre-slim
WORKDIR /app
RUN mkdir -p /usr/local/ksan/etc/
COPY ./core/backend/src/com/pspace/backend/lifecycle/ksanLifecycleManager_log_conf.xml /usr/local/ksan/etc/
COPY --from=build /src/target/ksanLifecycleManager.jar /usr/local/ksan/sbin/
COPY ./core/backend/src/com/pspace/backend/lifecycle/docker/start.sh /app/
CMD ["/app/start.sh"]