FROM maven:3.8.6-jdk-11 as libsbuild
WORKDIR /src
COPY ./core/src/com/pspace/ifs/ksan/libs/ /src/
RUN mvn -f /src/pom.xml package install
########################################################################
FROM maven:3.8.6-jdk-11 as build
WORKDIR /src
COPY --from=libsbuild /root/.m2 /root/.m2
COPY ./core/src/com/pspace/ifs/ksan/osd/ /src/
RUN mvn -f /src/pom.xml package
########################################################################
FROM openjdk:11-jre-slim
WORKDIR /app
RUN mkdir -p /usr/local/ksan/etc/
COPY --from=build /src/target/ksan-osd.jar /app
COPY ./core/src/com/pspace/ifs/ksan/osd/ksan-osd-log.xml /usr/local/ksan/etc/
COPY ./core/src/com/pspace/ifs/ksan/osd/docker/ksan-osd.sh /app
CMD ["/app/ksan-osd.sh"]