#!/usr/bin/env python3
"""
* Copyright (c) 2021 PSPACE, inc. KSAN Development Team ksan@pspace.co.kr
* KSAN is a suite of free software: you can redistribute it and/or modify it under the terms of
* the GNU General Public License as published by the Free Software Foundation, either version 
* 3 of the License.  See LICENSE for details
*
* 본 프로그램 및 관련 소스코드, 문서 등 모든 자료는 있는 그대로 제공이 됩니다.
* KSAN 프로젝트의 개발자 및 개발사는 이 프로그램을 사용한 결과에 따른 어떠한 책임도 지지 않습니다.
* KSAN 개발팀은 사전 공지, 허락, 동의 없이 KSAN 개발에 관련된 모든 결과물에 대한 LICENSE 방식을 변경 할 권리가 있습니다.
"""


import os, sys
import pdb
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from disk.disk_manage import *
from network.network_manage import *
from common.init import *

def main():
    # Server info
    ret, conf = GetConf(MonServicedConfPath)
    if ret is False:
        print('Check if configuration is done')
        sys.exit(-1)

    MgsIp = conf.mgs.MgsIp
    PortalPort = int(conf.mgs.IfsPortalPort)
    Res, Errmsg, Ret, AllServers = GetServerInfo(MgsIp, PortalPort)
    if Res != ResOk:
        print(Errmsg)
        sys.exit(-1)

    Res, Errmsg, Ret, AllDisks = GetDiskInfo(MgsIp, int(PortalPort), conf.mgs.IfsPortalKey)
    if Res != ResOk:
        print(Errmsg)

    ServerNetworks = dict()
    for Svr in AllServers:
        Res, Errmsg, Ret, Networks = GetNetworkInterface(MgsIp, PortalPort, ServerId=Svr.Id)
        if Res != ResOk:
            print(Errmsg)
        else:
            ServerNetworks[Svr.Id] = list()
            for Network in Networks:
                ServerNetworks[Svr.Id].append(Network)

    ShowInfo(AllServers, AllDisks, ServerNetworks)



def main2():
    # Server info
    ret, conf = GetConf(MonServicedConfPath)
    if ret is False:
        print('Check if configuration is done')
        sys.exit(-1)

    AllServersDetail = list()
    MgsIp = conf.mgs.MgsIp
    PortalPort = int(conf.mgs.IfsPortalPort)
    Res, Errmsg, Ret, AllServers = GetServerInfo(MgsIp, PortalPort)
    if Res != ResOk:
        print(Errmsg)
        return AllServersDetail

    for Svr in AllServers:
        Res, Errmsg, Ret, ServerDetail = GetServerInfo(MgsIp, PortalPort, ServerId=Svr.Id)
        if Res != ResOk:
            print(Errmsg)
        else:
            AllServersDetail.append(ServerDetail)
    return AllServersDetail


AllserversDetail = main2()
ShowSysInfo(AllserversDetail)
