#!/usr/bin/env python3
"""
* Copyright (c) 2021 PSPACE, inc. KSAN Development Team ksan@pspace.co.kr
* KSAN is a suite of free software: you can redistribute it and/or modify it under the terms of
* the GNU General Public License as published by the Free Software Foundation, either version 
* 3 of the License.  See LICENSE for details
*
* 본 프로그램 및 관련 소스코드, 문서 등 모든 자료는 있는 그대로 제공이 됩니다.
* KSAN 프로젝트의 개발자 및 개발사는 이 프로그램을 사용한 결과에 따른 어떠한 책임도 지지 않습니다.
* KSAN 개발팀은 사전 공지, 허락, 동의 없이 KSAN 개발에 관련된 모든 결과물에 대한 LICENSE 방식을 변경 할 권리가 있습니다.
"""

import os, sys
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from ksan.common.init import InitMonServicedConf, read_conf
from ksan.server.server_manage import *
import pdb


class MyOptionParser(OptionParser):
    def print_help(self):
        Usage = """
        Usage: ksanServer {update|show|status} [option]
                unregister    -S <server id>                                 : Unregister server from servers pool
                update    -S <server id> -n <server name> -e <Description>   : Update server info 
                list      -S <server id>                                     : Show the registered server info
        [options]
                -S                                                           : Server Id    
                -e                                                           : Description
                -n                                                           : Server Name
                -L                                                           : Show info in detail
                -h, --help                                                   : show this help message and exit
"""
        print(Usage)


if __name__ == '__main__':
    usage = "Usage: %prog {remove|update|list} [option]"
    parser = MyOptionParser(usage=usage)
    parser.add_option('-S', "--Id", dest="ServerId", help='Server Id')
    parser.add_option('-e', "--Description", dest="Description", default='', help='Server Description')
    parser.add_option('-n', "--Name", dest="Name", default=None, help='Server Name')
    parser.add_option('-L', "--Detail", dest="Detail", action='store_true', help='Server Info in detail')
    parser.add_option('-s', "--State", dest="State", help='Server State')
    parser.add_option('-d', "--Debug", dest="debug", action='store_true', default=False, help='debug mode')
    parser.add_option('-A', "--LoadAverage", dest="LoadAverage", default=False, help='LoadAverage')

    options, args = parser.parse_args()
    if len(args) != 1:
        parser.print_help()
        sys.exit(-1)

    IfsPortalIp = '127.0.0.1'
    IfsPortalPort = 5443
    IfsMqPort = 5672
    ret, conf = read_conf(MonServicedConfPath)
    if ret is True:
        IfsPortalIp = conf['mgs']['MgsIp']
        IfsPortalPort = int(conf['mgs']['IfsPortalPort'])
        IfsMqPort = int(conf['mgs']['MqPort'])

    logger = None
    if options.debug is True:
        logger = Logging(loglevel='debug')
        logger = logger.create()

    if args[0] == 'init':
        InitMonServicedConf()
    elif args[0] == 'add':
        Res, Errmsg, Ret = AddServer(IfsPortalIp, IfsPortalPort, options.Description, logger=logger)
        if Res == ResOk:
            print(Ret.Result, Ret.Message)
        else:
            print(Errmsg)
    elif args[0] == 'unregister':
        if options.ServerId is None:
            parser.print_help()
            sys.exit(-1)
        Res, Errmsg, Ret = RemoveServer(IfsPortalIp, IfsPortalPort, options.ServerId, logger=logger)
        if Res == ResOk:
            print(Ret.Result, Ret.Message)
        else:
            print(Errmsg)
    elif args[0] == 'update':
        if options.ServerId is None:
            parser.print_help()
            sys.exit(-1)

        Res, Errmsg, Ret = UpdateServerInfo(IfsPortalIp, IfsPortalPort, options.ServerId, Name=options.Name,
                                            Description=options.Description, State=options.State, logger=logger)
        if Res == ResOk:
            print(Ret.Result, Ret.Message)
        else:
            print(Errmsg)

    elif args[0] == 'update_state':
        if options.ServerId is None:
            parser.print_help()
            sys.exit(-1)

        Res, Errmsg, Ret = UpdateServerInfo(IfsPortalIp, IfsPortalPort, options.ServerId, State=options.State, logger=logger)
        if Res == ResOk:
            print(Ret.Result, Ret.Message)
        else:
            print(Errmsg)
    elif args[0] == 'list':
        Detail = False
        if options.Detail:
            Detail = True
        Res, errmsg, Ret, Data = GetServerInfo(IfsPortalIp, IfsPortalPort, ServerId=options.ServerId, logger=logger)
        if Res == ResOk:
            if Ret.Result == ResultSuccess:
                ShowServerInfo(Data, Id=options.ServerId, Detail=options.Detail)
            else:
                print(Ret.Result, Ret.Message)
        else:
            print(errmsg)
    elif args[0] == 'check':
        if options.name is None:
            parser.print_help()
            sys.exit(-1)
        Res, Errmsg, Ret = server_exist_check_with_servername(IfsPortalIp, IfsPortalPort, options.Name,
                                                              ExcludeServerId=options.ServerId, logger=logger)
        if Res == ResOk:
            print(Ret.Result, Ret.Message, Ret.Data)
        else:
            print(Errmsg)
    else:
        parser.print_help()
