#!/usr/bin/env python3
"""
* Copyright (c) 2021 PSPACE, inc. KSAN Development Team ksan@pspace.co.kr
* KSAN is a suite of free software: you can redistribute it and/or modify it under the terms of
* the GNU General Public License as published by the Free Software Foundation, either version 
* 3 of the License.  See LICENSE for details
*
* 본 프로그램 및 관련 소스코드, 문서 등 모든 자료는 있는 그대로 제공이 됩니다.
* KSAN 프로젝트의 개발자 및 개발사는 이 프로그램을 사용한 결과에 따른 어떠한 책임도 지지 않습니다.
* KSAN 개발팀은 사전 공지, 허락, 동의 없이 KSAN 개발에 관련된 모든 결과물에 대한 LICENSE 방식을 변경 할 권리가 있습니다.
"""


import os, sys
import pdb
sys.path.append(os.path.dirname(os.path.abspath(os.path.dirname(__file__))))
from ksan.disk.disk_manage import *
from ksan.network.network_manage import *
from ksan.common.init import *

def main():
    # Server info
    ret, conf = GetConf(MonServicedConfPath)
    if ret is False:
        print('Check if configuration is done')
        sys.exit(-1)

    MgsIp = conf.mgs.MgsIp
    PortalPort = int(conf.mgs.IfsPortalPort)
    Res, Errmsg, Ret, AllServers = GetServerInfo(MgsIp, PortalPort)
    if Res != ResOk:
        print(Errmsg)
        sys.exit(-1)

    Res, Errmsg, Ret, AllDisks = GetDiskInfo(MgsIp, int(PortalPort))
    if Res != ResOk:
        print(Errmsg)

    ServerNetworks = dict()
    for Svr in AllServers:
        Res, Errmsg, Ret, Networks = GetNetworkInterface(MgsIp, PortalPort, ServerId=Svr.Id)
        if Res != ResOk:
            print(Errmsg)
        else:
            ServerNetworks[Svr.Id] = list()
            for Network in Networks:
                ServerNetworks[Svr.Id].append(Network)

    ShowInfo(AllServers, AllDisks, ServerNetworks)

def ShowInfo(AllServers, AllDisks, ServerNetworks):
    print("[ SERVER / NETWORK / DISK ]")
    ServerTitleLine = "%s" % ('=' * 197)
    print(ServerTitleLine)
    ServerTitle = "|%s|%s|%s|%s|%s|%s|%s|%s|" % ('Name'.center(21), 'CpuModel'.center(31),
                                    'Clock'.center(21), 'State'.center(21), 'LoadAvg(1M 5M 15M)'.center(19),
                                    'MemTotal'.center(21), 'MemUsed'.center(21), 'Id'.center(31))
    print(ServerTitle)
    print(ServerTitleLine)

    ServerDataLine = "%s" % ('-' * 197)

    for idx, Svr in enumerate(AllServers):
        if idx > 0:
            print(ServerDataLine)
        ServerData = "|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|" % \
            (Svr.Name.center(21),
                '{:31.31}'.format(Svr.CpuModel.center(31)), str(Svr.Clock).center(21),
                Svr.State.center(21), str(Svr.LoadAverage1M).center(5), str(Svr.LoadAverage5M).center(5),
                str(Svr.LoadAverage15M).center(5), str(int(Svr.MemoryTotal)).center(20),
                str(int(Svr.MemoryUsed)).center(20), Svr.Id.center(30))
        print(ServerData)
        print(ServerDataLine)

        NetworkTitle = "%s|%s|%s|%s|%s|%s|%s|" % (' '.center(70), 'Network Device'.center(20) ,
                                               'IpAddress'.center(20), 'Rx'.center(10), 'Tx'.center(10),
                                               'LinkStatus'.center(20), 'Id'.center(40))
        print(NetworkTitle)
        NetworkTitleLine = "%s%s" % (' ' * 70, '-' * 127)
        print(NetworkTitleLine)

        for interface in ServerNetworks[Svr.Id]:
            NetData = "%s|%s|%s|%s|%s|%s|%s|" % (' '.center(70),
                                                 '{:20.20}'.format(interface.Name.center(20)),
                                                 '{:20.20}'.format(interface.IpAddress.center(20)),
                                                 str(int(interface.Rx)).center(10),
                                                 str(int(interface.Tx)).center(10), interface.LinkState.center(20),
                                                 interface.Id.center(40),)  # svr.ModDate.center(20), svr.ModId.center(20), svr.ModName.center(20), svr.Id.center(30))
            print(NetData)

        DiskTitleLine = "%s%s" % (' ' * 54, '-' * 143)
        print(DiskTitleLine)
        DiskTitle = "%s|%s|%s|%s|%s|%s|%s|%s|" % (' ' * 54, 'DiskId'.center(40), 'Path'.center(15),
                                              'State'.center(10), 'Total'.center(20), 'Used'.center(20), 'Free'.center(20), 'RwMode'.center(10))
        print(DiskTitle)
        print(DiskTitleLine)
        for disk in AllDisks:
            DiskSvr = DeserializeResponse(disk.Server, ServerItemsModule)
            if Svr.Id != DiskSvr.Id:
                continue

            # svr = GetDataFromBody(disk.Server, ServerItemsModule)
            DiskData = "%s|%s|%s|%s|%s|%s|%s|%s|" % (' ' * 54, str(disk.Id).center(40),
                                           '{:15.15}'.format(disk.Path.center(15)),
                                           disk.State.center(10), str(int(disk.TotalSize)).center(20),
                                           str(int(disk.UsedSize)).center(20),
                                           str(int(disk.TotalSize - disk.UsedSize - disk.ReservedSize)).center(20),
                                           disk.RwMode.center(10))
            print(DiskData)

    print(ServerTitleLine)
    print()
    """
    print("[ NETWORK ]")
    compart = "%s" % ('-' * 209)
    print(compart)
    title ="|%s|%s|%s|%s|%s|%s|%s|%s|" % ('Id'.center(40), 'Server Name'.center(40),  'Network Device'.center(20),
         'IpAddress'.center(20), 'Rx'.center(10), 'Tx'.center(10),
        'LinkStatus'.center(20), 'ServerId'.center(40))

    print(title)
    print(compart)
    for Svr in AllServers:
        for interface in ServerNetworks[Svr.Id]:
            _nic =" %s %s %s %s %s %s %s %s" % (interface.Id.center(40), '{:40.40}'.format(Svr.Name.center(40)),
                                      '{:20.20}'.format(interface.Name.center(20)),
                                      '{:20.20}'.format(interface.IpAddress.center(20)),
                                       str(int(interface.Rx)).center(10), str(int(interface.Tx)).center(10), interface.LinkState.center(20), Svr.Id.center(40)) # svr.ModDate.center(20), svr.ModId.center(20), svr.ModName.center(20), svr.Id.center(30))
            print(_nic)
    """

#main()


def main2():
    # Server info
    ret, conf = GetConf(MonServicedConfPath)
    if ret is False:
        print('Check if configuration is done')
        sys.exit(-1)

    AllServersDetail = list()
    MgsIp = conf.mgs.MgsIp
    PortalPort = int(conf.mgs.IfsPortalPort)
    Res, Errmsg, Ret, AllServers = GetServerInfo(MgsIp, PortalPort)
    if Res != ResOk:
        print(Errmsg)
        return AllServersDetail

    for Svr in AllServers:
        Res, Errmsg, Ret, ServerDetail = GetServerInfo(MgsIp, PortalPort, ServerId=Svr.Id)
        if Res != ResOk:
            print(Errmsg)
        else:
            AllServersDetail.append(ServerDetail)
    return AllServersDetail


def ShowInfo1(AllServersDetail):
    print("[ SERVER / NETWORK / DISK ]")
    ServerTitleLine = "%s" % ('=' * 197)
    print(ServerTitleLine)
    ServerTitle = "|%s|%s|%s|%s|%s|%s|%s|%s|%s|" % ('Name'.center(21), 'CpuModel'.center(20),
                                                 'Clock'.center(10), 'State'.center(10),
                                                 'LoadAvg(1M 5M 15M)'.center(19),
                                                 'MemTotal(MB)'.center(15), 'MemUsed(MB)'.center(15), 'Id'.center(38),
                                                    ' '.center(39))
    print(ServerTitle)
    print(ServerTitleLine)

    ServerDataLine = "%s" % ('-' * 197)

    for idx, Svr in enumerate(AllServersDetail):
        if idx > 0:
            print(ServerDataLine)
        ServerData = "|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|" % \
            (Svr.Name.center(21),
                '{:20.20}'.format(Svr.CpuModel.center(20)), str(Svr.Clock).center(10),
                Svr.State.center(10), str(Svr.LoadAverage1M).center(6), str(Svr.LoadAverage5M).center(5),
                str(Svr.LoadAverage15M).center(6), str(int(Svr.MemoryTotal/1000000)).center(15),
                str(int(Svr.MemoryUsed/1000000)).center(15), Svr.Id.center(38))
        print(ServerData)
        print(ServerDataLine)

        DiskTitleLine = "%s%s" % (' ' * 21, '-' * 176)
        DiskTitle = "%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|" % (' ' * 21, 'DiskId'.center(40), 'Path'.center(15),
                                                           'State'.center(10), 'Total Size(MB)'.center(15),
                                                           'Used Size(MB)'.center(15),
                                                           'Free Size(MB)'.center(15), 'Total Inode'.center(15),
                                                           'Used Inode'.center(15), 'Free Inode'.center(15),
                                                           'RwMode'.center(10))
        print(DiskTitle)
        print(DiskTitleLine)

        for disk in Svr.Disks:
            # svr = GetDataFromBody(disk.Server, ServerItemsModule)
            DiskData = "%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|%s|" % (' ' * 21, str(disk.Id).center(40),
                                                     '{:15.15}'.format(disk.Path.center(15)),
                                                     disk.State.center(10), str(int(disk.TotalSize/1000000)).center(15),
                                                     str(int(disk.UsedSize/1000000)).center(15),
                                                     str(int(
                                                         (disk.TotalSize - disk.UsedSize - disk.ReservedSize)/1000000)).center(
                                                         15), str(int(disk.TotalInode)).center(15), str(int(disk.UsedInode)).center(15), str(int(
                                                         disk.TotalInode - disk.UsedInode - disk.ReservedInode)).center(
                                                         15),
                                                     disk.RwMode.center(10))
            print(DiskData)
            print(DiskTitleLine)



        NetworkTitle = "%s|%s|%s|%s|%s|%s|%s|" % (' '.center(70), 'Network Device'.center(20) ,
                                               'IpAddress'.center(20), 'Rx'.center(10), 'Tx'.center(10),
                                               'LinkStatus'.center(20), 'Id'.center(40))
        print(NetworkTitle)
        NetworkTitleLine = "%s%s" % (' ' * 70, '-' * 127)
        print(NetworkTitleLine)

        for net in Svr.NetworkInterfaces:
            NetData = "%s|%s|%s|%s|%s|%s|%s|" % (' '.center(70),
                                                 '{:20.20}'.format(net.Name.center(20)),
                                                 '{:20.20}'.format(net.IpAddress.center(20)),
                                                 str(int(net.Rx)).center(10),
                                                 str(int(net.Tx)).center(10), net.LinkState.center(20),
                                                 net.Id.center(40),)  # svr.ModDate.center(20), svr.ModId.center(20), svr.ModName.center(20), svr.Id.center(30))
            print(NetData)


    print(ServerTitleLine)
    print()


AllserversDetail = main2()
ShowInfo1(AllserversDetail)

