FROM maven:3.8.6-jdk-11 as build
WORKDIR /src
COPY . .
RUN mvn package

FROM openjdk:11-jre-slim
WORKDIR /app
RUN mkdir -p /app/logs
COPY --from=build /src/target/ksanMetering /app
COPY ./resources/ksan-metering.xml /app
COPY ./resources/start.sh /app
CMD ["/app/start.sh"]